export const TODOS = [
  'Prepare the dough for white bread',
  'Knead and shape the bread rolls',
  'Let the dough rest and ferment',
  'Preheat the oven to the appropriate temperature',
  'Bake the bread for the specified time',
  'Prepare the mixture for the cakes',
  'Fill the cakes with the mixture and seal them properly',
  'Bake the cakes until they are golden',
  'Decorate the cakes with icing or powdered sugar',
  'Prepare the dough for the turnovers',
  'Fill the turnovers with the chosen filling',
  'Close and seal the turnovers',
  'Bake the turnovers until they are flaky and golden brown',
  'Mix and prepare the ingredients for the custard filling',
  'Bake the custard tarts until they are set and lightly browned',
  'Prepare the dough for the cinnamon rolls',
  'Roll and shape the dough into cinnamon rolls',
  'Let the cinnamon rolls rise before baking',
  'Bake the cinnamon rolls until they are fluffy and aromatic',
  'Clean and sanitize the baking equipment and work area',
]